config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  resource :contacts, only: [:new, :create]
  get 'contacts/thanks' => 'contacts#thanks'
  devise_for :admins
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :shops
  end

  devise_scope :member do
    post 'members/guest_sign_in' => 'members/sessions#new_guest'
  end
  devise_for :members
  scope module: :member do
    resources :members, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
    end

    get 'members/:id/bookmarks' => 'members#bookmarks', as: 'bookmarks'
    get 'members/:id/tweet_likes' => 'members#tweet_likes', as: 'tweet_likes'
    get '/members/:id/unsubscribe' => 'members#unsubscribe', as: 'unsubscribe'
    patch '/members/:id/withdrawal' => 'members#withdrawal', as: 'withdrawal'

    resources :tweets, only: [:index, :show, :new, :create, :destroy] do
      resource :tweet_likes, only: [:create, :destroy]
      resources :tweet_comments, only: [:create, :destroy]
    end

    get 'shops/search' => 'shops#search'
    get 'shops/ranking' => 'shops#ranking'
    get 'shops/map' => 'shops#map'
    resources :shops, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
      resources :reviews
    end

    resources :notifications, only: [:index]

    get 'genres/cake' => 'genres#cake'
    get 'genres/macaron' => 'genres#macaron'
    get 'genres/chocolate' => 'genres#chocolate'
    get 'genres/parfait' => 'genres#parfait'
    get 'genres/cafe' => 'genres#cafe'
    get 'genres/shaved_ice' => 'genres#shaved_ice'
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :genre
  has_many :shop_images, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  attachment :main_image
  accepts_attachments_for :shop_images, attachment: :image

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, presence: true, length: { maximum: 30 }
  validates :address, presence: true
  validates :nearest_station, presence: true
  validates :business_hours, presence: true
  validates :regular_holiday, presence: true
  validates :caption, presence: true, length: { maximum: 300 }
  validates :phone_number, presence: true
  validates :main_image, presence: true

  # ユーザーがお店をブックマークしているかどうかの判定メソッド
  def bookmarked_by?(member)
    bookmarks.where(member_id: member.id).exists?
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @shops = Shop.all.page(params[:page]).per(10)
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def new
    @shop = Shop.new
    @genres = Genre.all
  end

  def create
    @genres = Genre.all
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to admin_shop_path(@shop), noice: "店舗情報を登録しました"
    else
      flash.now[:alert] = "店舗情報の登録を失敗しました"
      render :new
    end
  end

  def edit
    @shop = Shop.find(params[:id])
    @genres = Genre.all
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to admin_shop_path(@shop), noice: "店舗情報を更新しました"
    else
      flash.now[:alert] = "店舗情報の更新を失敗しました"
      render :edit
    end
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    redirect_to request.referer, notice: "店舗情報を削除しました"
  end

  private

  def shop_params
    params.require(:shop).permit(
      :genre_id,
      :name,
      :phone_number,
      :address,
      :latitude,
      :longitude,
      :nearest_station,
      :business_hours,
      :regular_holiday,
      :main_image,
      :caption,
      shop_images_images: []
    )
  end
end

app/controllers/member/shops_controller.rb
class Member::ShopsController < ApplicationController
  def index
    @shops = Shop.all.page(params[:page]).per(5).order(created_at: "DESC")
  end

  def show
    @shop = Shop.find(params[:id])
    @reviews = @shop.reviews
  end

  def search
    @q = Shop.ransack(params[:q])
    @shops = @q.result(distinct: true).page(params[:page]).per(5)
  end

  def ranking
    # shopのランキング形式用
    @shops = Shop.all
    @shops_rank = @shops.sort_by do |shop|
      shop.reviews.average(:rate).nil? ? 0 : shop.reviews.average(:rate)
    end.reverse
  end

  def map
    @shop = Shop.find(params[:id])
  end

  private

  def shops_params
    params.require(:shop).permit(
      :genre_id,
      :name,
      :phone_number,
      :address,
      :latitude,
      :longitude,
      :nearest_station,
      :business_hours,
      :regular_holiday,
      :main_image_id,
      :caption,
      shop_images_images: []
    )
  end
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/member/shops_helper.rb
module Member::ShopsHelper
end

app/views/admin/shops/edit.html.erb
<!-- members/edit・contacts/newのクラスを引用 -->
<h3 class="page-heading">Shop Edit</h3>
<div class="my-page-edit">
  <div class="edit-profile">
    <%= form_with model: @shop, url: admin_shop_path(@shop), method: :patch, local: true do |f| %>
    <%= render 'layouts/error_messages', model: @shop %>
      <table class="table">
        <tr>
          <td class="admin-shop-text"><%= f.label :"店舗名"%></td>
          <td><%= f.text_field :name, placeholder: "例）ブラウンカフェ", class: "edit-profile-form" %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"ジャンル" %></td>
          <td><%= f.collection_select :genre_id, @genres, :id, :name, {prompt: "--選択してください--"} %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"メイン写真" %></td>
          <td><%= f.attachment_field :main_image %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"写真(3枚)" %></td>
          <td><%= f.attachment_field :shop_images_images, multiple: true %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"紹介・説明" %></td>
          <td><%= f.text_area :caption, class: "edit-profile-form" %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"住所" %></td>
          <td><%= f.text_field :address, placeholder: "例）東京都品川区1-1-1 品川ハイツ3階", class: "edit-profile-form" %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"最寄り駅" %></td>
          <td><%= f.text_field :nearest_station, placeholder: "例）JR品川駅 徒歩5分", class: "edit-profile-form" %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"電話番号" %></td>
          <td><%= f.telephone_field :phone_number, placeholder: "例）03-1234-5678", class: "edit-profile-form" %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"営業時間" %></td>
          <td><%= f.text_field :business_hours, placeholder: "例）11:00〜20:00", class: "edit-profile-form" %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"定休日" %></td>
          <td><%= f.text_field :regular_holiday, placeholder: "例）毎週木曜日", class: "edit-profile-form" %></td>
        </tr>
        <tr>
          <td></td>
          <td style="text-align: left;"><%= f.submit '変更', class: "edit-profile-btn" %></td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/admin/shops/index.html.erb
<h3 class="page-heading">Shop</h3>
<!-- members/shopのクラス引用 -->
<div class="shop-container">
  <table>
    <thead>
      <tr>
        <th>店舗名</th>
        <th>ジャンル</th>
        <th>住所</th>
        <th>電話番号</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <div class="admin-shops-text">
          <td><%= link_to shop.name, admin_shop_path(shop) %></td>
          <td><%= shop.genre.name %></td>
          <td><%= shop.address %></td>
          <td><%= shop.phone_number %></td>
          <td>
            <!-- member/withdrawalのボタンを引用 -->
            <% if admin_signed_in? %>
              <%= link_to "編集", edit_admin_shop_path(shop), class: "no-withdrawal-btn" %>
              <%= link_to "削除", admin_shop_path(shop), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "withdrawal-btn" %>
            <% end %>
          </td>
        </div>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @shops %>
</div>

app/views/admin/shops/new.html.erb
<!-- members/edit・contacts/newのクラスを引用 -->
<h3 class="page-heading">Shop New</h3>
<div class="my-page-edit">
  <div class="edit-profile">
    <%= form_with model: @shop, url: admin_shops_path, local: true do |f| %>
    <%= render 'layouts/error_messages', model: @shop %>
      <table class="table">
        <tr>
          <td class="admin-shop-text"><%= f.label :"店舗名"%></td>
          <td><%= f.text_field :name, placeholder: "例）ブラウンカフェ", class: "edit-profile-form" %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"ジャンル" %></td>
          <td><%= f.collection_select :genre_id, @genres, :id, :name, {prompt: "--選択してください--"} %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"メイン写真" %></td>
          <td><%= f.attachment_field :main_image %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"写真(3枚)" %></td>
          <td><%= f.attachment_field :shop_images_images, multiple: true %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"紹介・説明" %></td>
          <td><%= f.text_area :caption, class: "contacts-form" %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"住所" %></td>
          <td><%= f.text_field :address, placeholder: "例）東京都品川区1-1-1 品川ハイツ3階", class: "edit-profile-form" %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"最寄り駅" %></td>
          <td><%= f.text_field :nearest_station, placeholder: "例）JR品川駅 徒歩5分", class: "edit-profile-form" %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"電話番号" %></td>
          <td><%= f.text_field :phone_number, placeholder: "例）03-1234-5678", class: "edit-profile-form" %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"営業時間" %></td>
          <td><%= f.text_field :business_hours, placeholder: "例）11:00〜20:00", class: "edit-profile-form" %></td>
        </tr>
        <tr>
          <td class="admin-shop-text"><%= f.label :"定休日" %></td>
          <td><%= f.text_field :regular_holiday, placeholder: "例）毎週木曜日", class: "edit-profile-form" %></td>
        </tr>
        <tr>
          <td></td>
          <td style="text-align: left;"><%= f.submit '店舗情報登録', class: "edit-profile-btn" %></td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/admin/shops/show.html.erb
<!-- member/shops/showから引用 -->
<div class="show-shop-container">
  <div class="show-shop-top">
    <span class="show-shop-name"><%= @shop.name %><p class="shop-text">&emsp;/&emsp;<%= @shop.genre.name %></p></span>
    <ul class="review-list">
      <span id="star-average-<%= @shop.id %>"></span>
      <span class="review-list-item"><%= @shop.reviews.average(:rate).to_f.round(1) %>&emsp;</span>
      <%= render partial: 'member/reviews/star_average', locals: { shop: @shop } %>
    </ul>
  </div>
  <hr class="border">
  <div class="show-main-image">
    <%= attachment_image_tag @shop, :main_image, class: "main-image" %>
  </div>
  <div class="show-sub-image">
    <% @shop.shop_images.each do |shop_image| %>
  　　  <%= attachment_image_tag shop_image, :image, class: "sub-image" %>
  　<% end %>
  </div>
  <hr class="border-sm">
  <div class="shop-caption">
    <h5>店鋪紹介</h5>
    <%= simple_format(@shop.caption) %>
  </div>
  <hr class="border-sm">
  <div class="shop-info">
    <h5>店鋪情報</h5>
    <table class="table shop-table">
      <tbody>
        <tr>
          <th width="100" style="background: #fefae6;">住所</th>
          <td><%= @shop.address %></td>
        </tr>
        <tr>
          <th width="100" style="background: #fefae6;">電話番号</th>
          <td><%= @shop.phone_number %></td>
        </tr>
        <tr>
          <th width="100" style="background: #fefae6;">営業時間</th>
          <td><%= @shop.business_hours %></td>
        </tr>
        <tr>
          <th width="100" style="background: #fefae6;">定休日</th>
          <td><%= @shop.regular_holiday %></td>
        </tr>
        <tr>
          <th width="100" style="background: #fefae6;">アクセス</th>
          <td><%= @shop.nearest_station %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <hr class="border-sm">
  <div class="map-area">
    <h5>アクセス</h5>
    <%= render 'layouts/map' %>
    <!--mapの表示-->
    <div id="map"></div>
  </div>
</div>