config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  resource :contacts, only: [:new, :create]
  get 'contacts/thanks' => 'contacts#thanks'
  devise_for :admins
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :shops
  end

  devise_scope :member do
    post 'members/guest_sign_in' => 'members/sessions#new_guest'
  end
  devise_for :members
  scope module: :member do
    resources :members, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
    end

    get 'members/:id/bookmarks' => 'members#bookmarks', as: 'bookmarks'
    get 'members/:id/tweet_likes' => 'members#tweet_likes', as: 'tweet_likes'
    get '/members/:id/unsubscribe' => 'members#unsubscribe', as: 'unsubscribe'
    patch '/members/:id/withdrawal' => 'members#withdrawal', as: 'withdrawal'

    resources :tweets, only: [:index, :show, :new, :create, :destroy] do
      resource :tweet_likes, only: [:create, :destroy]
      resources :tweet_comments, only: [:create, :destroy]
    end

    get 'shops/search' => 'shops#search'
    get 'shops/ranking' => 'shops#ranking'
    get 'shops/map' => 'shops#map'
    resources :shops, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
      resources :reviews
    end

    resources :notifications, only: [:index]

    get 'genres/cake' => 'genres#cake'
    get 'genres/macaron' => 'genres#macaron'
    get 'genres/chocolate' => 'genres#chocolate'
    get 'genres/parfait' => 'genres#parfait'
    get 'genres/cafe' => 'genres#cafe'
    get 'genres/shaved_ice' => 'genres#shaved_ice'
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :shops
  validates :name, presence: true, length: { maximum: 10 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to request.referer, notice: "ジャンルの作成が成功しました"
    else
      flash.now[:alert] = "登録に失敗しました"
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
    @genres = Genre.all
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンル名を変更しました"
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to request.referer, notice: "ジャンルの削除に成功しました"
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/member/genres_controller.rb
class Member::GenresController < ApplicationController
  def cake
    @cakes_shops = Shop.where(genre_id: 1).page(params[:page]).per(10)
  end

  def macaron
    @macaron_shops = Shop.where(genre_id: 2).page(params[:page]).per(10)
  end

  def chocolate
    @chocolate_shops = Shop.where(genre_id: 3).page(params[:page]).per(10)
  end

  def parfait
    @parfait_shops = Shop.where(genre_id: 4).page(params[:page]).per(10)
  end

  def cafe
    @cafe_shops = Shop.where(genre_id: 5).page(params[:page]).per(10)
  end

  def shaved_ice
    @shaved_ice_shops = Shop.where(genre_id: 6).page(params[:page]).per(10)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/member/genres_helper.rb
module Member::GenresHelper
end

app/views/admin/genres/edit.html.erb
<h3 class="page-heading">Genre Edit</h3>
<!-- 登録ジャンル一覧表示 -->
<!-- members/shopのクラス引用 -->
<div class="shop-container">
  <!-- 編集欄 -->
  <div class="edit-genre">
    <%= form_with model: @genre, url: admin_genre_path(@genre), method: :patch, local: true do |f| %>
    <%= render 'layouts/error_messages', model: @genre %>
      <% f.label :"ジャンル名"%>
      <%= f.text_field :name, class: "genre-form" %>
      <%= f.submit '変更', class: "genre-btn" %>
    <% end %>
  </div>
　<table class="table">
    <tr>
      <th>ジャンル名</th>
      <th>登録件数</th>
    </tr>
    <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
      <!-- member/withdrawalのボタンを引用 -->
      <td>
        <%= link_to "編集", edit_admin_genre_path(genre), class: "no-withdrawal-btn" %>
        <%= link_to "削除", admin_genre_path(genre), method: :delete, data: { confilm: "本当に削除しますか" }, class: "withdrawal-btn" %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/genres/index.html.erb
<h3 class="page-heading">Genre</h3>
<!-- 登録ジャンル一覧表示 -->
<!-- members/shopのクラス引用 -->
<div class="shop-container">
  <!-- 新規登録欄 -->
  <div class="new-genre">
    <%= form_with model: @genre, url: admin_genres_path, local: true do |f| %>
    <%= render 'layouts/error_messages', model: @genre %>
      <% f.label :"ジャンル名" %>
      <%= f.text_field :name, placeholder: "ジャンル名を入力", class: "genre-form" %>
      <%= f.submit '登録', class: "genre-btn" %>
    <% end %>
  </div>
  <table class="table">
    <tr>
      <th>ジャンル名</th>
      <th>登録件数</th>
    </tr>
    <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
      <!-- member/withdrawalのボタンを引用 -->
      <td>
        <% if admin_signed_in? %>
          <%= link_to "編集", edit_admin_genre_path(genre), class: "no-withdrawal-btn" %>
          <%= link_to "削除", admin_genre_path(genre), method: :delete, data: { confilm: "本当に削除しますか" }, class: "withdrawal-btn" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
</div>