config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  resource :contacts, only: [:new, :create]
  get 'contacts/thanks' => 'contacts#thanks'
  devise_for :admins
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :shops
  end

  devise_scope :member do
    post 'members/guest_sign_in' => 'members/sessions#new_guest'
  end
  devise_for :members
  scope module: :member do
    resources :members, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
    end

    get 'members/:id/bookmarks' => 'members#bookmarks', as: 'bookmarks'
    get 'members/:id/tweet_likes' => 'members#tweet_likes', as: 'tweet_likes'
    get '/members/:id/unsubscribe' => 'members#unsubscribe', as: 'unsubscribe'
    patch '/members/:id/withdrawal' => 'members#withdrawal', as: 'withdrawal'

    resources :tweets, only: [:index, :show, :new, :create, :destroy] do
      resource :tweet_likes, only: [:create, :destroy]
      resources :tweet_comments, only: [:create, :destroy]
    end

    get 'shops/search' => 'shops#search'
    get 'shops/ranking' => 'shops#ranking'
    get 'shops/map' => 'shops#map'
    resources :shops, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
      resources :reviews
    end

    resources :notifications, only: [:index]

    get 'genres/cake' => 'genres#cake'
    get 'genres/macaron' => 'genres#macaron'
    get 'genres/chocolate' => 'genres#chocolate'
    get 'genres/parfait' => 'genres#parfait'
    get 'genres/cafe' => 'genres#cafe'
    get 'genres/shaved_ice' => 'genres#shaved_ice'
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @shops = Shop.all.page(params[:page]).per(10)
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def new
    @shop = Shop.new
    @genres = Genre.all
  end

  def create
    @genres = Genre.all
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to admin_shop_path(@shop), noice: "店舗情報を登録しました"
    else
      flash.now[:alert] = "店舗情報の登録を失敗しました"
      render :new
    end
  end

  def edit
    @shop = Shop.find(params[:id])
    @genres = Genre.all
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to admin_shop_path(@shop), noice: "店舗情報を更新しました"
    else
      flash.now[:alert] = "店舗情報の更新を失敗しました"
      render :edit
    end
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    redirect_to request.referer, notice: "店舗情報を削除しました"
  end

  private

  def shop_params
    params.require(:shop).permit(
      :genre_id,
      :name,
      :phone_number,
      :address,
      :latitude,
      :longitude,
      :nearest_station,
      :business_hours,
      :regular_holiday,
      :main_image,
      :caption,
      shop_images_images: []
    )
  end
end

app/controllers/member/bookmarks_controller.rb
class Member::BookmarksController < ApplicationController
  def create
    @shop = Shop.find(params[:shop_id])
    bookmark = current_member.bookmarks.build(shop_id: @shop.id)
    bookmark.save
    # redirect_to request.referer
  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    bookmark = current_member.bookmarks.find_by(shop_id: @shop.id)
    bookmark.destroy
    # redirect_to request.referer
  end
end

app/controllers/member/genres_controller.rb
class Member::GenresController < ApplicationController
  def cake
    @cakes_shops = Shop.where(genre_id: 1).page(params[:page]).per(10)
  end

  def macaron
    @macaron_shops = Shop.where(genre_id: 2).page(params[:page]).per(10)
  end

  def chocolate
    @chocolate_shops = Shop.where(genre_id: 3).page(params[:page]).per(10)
  end

  def parfait
    @parfait_shops = Shop.where(genre_id: 4).page(params[:page]).per(10)
  end

  def cafe
    @cafe_shops = Shop.where(genre_id: 5).page(params[:page]).per(10)
  end

  def shaved_ice
    @shaved_ice_shops = Shop.where(genre_id: 6).page(params[:page]).per(10)
  end
end

app/controllers/member/members_controller.rb
class Member::MembersController < ApplicationController
  # ログイン中のユーザーidと編集したいユーザーidが等しいか判定する。
  before_action :ensure_current_member, { only: [:edit, :update, :withdrawal] }
  def ensure_current_member
    unless current_member.id == params[:id].to_i
      redirect_to member_path(current_member), alert: "権限がありません"
    end
  end

  def show
    @member = Member.find(params[:id])
    @tweets = @member.tweets.page(params[:page]).per(12).order(created_at: "DESC")
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    # ゲストユーザーの変更を制限するため
    if @member.email == 'guest@example.com'
      redirect_to member_path(@member), alert: 'ゲストユーザーは編集できません'
    # 通常ユーザーの編集内容を保存
    elsif @member.update(member_params)
      redirect_to member_path(@member), notice: "更新に成功しました"
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  def withdrawal
    @member = Member.find(params[:id])
    # ゲストユーザの削除を制限するため
    if @member.email == 'guest@example.com'
      redirect_to member_path(@member), alert: "ゲストユーザーは削除出来ません"
    else
      # is_deletedカラムをtrueに変更することにより削除フラグを立てる
      @member.update(is_deleted: true)
      reset_session
      flash[:notice] = "退会処理を実行いたしました"
      redirect_to root_path
    end
  end

  # ブックマークの一覧表示用
  def bookmarks
    @bookmarks = current_member.bookmarks.page(params[:page]).per(10)
  end

  # いいねをしたつぶやきの一覧表示用
  def tweet_likes
    @member = Member.find(params[:id])
    @tweet_likes = @member.tweet_likes.page(params[:page]).per(9)
  end

  # フォロー画面表示用
  def follows
    member = Member.find(params[:id])
    @members = member.followings.page(params[:page]).per(10)
  end

  # フォロワー画面表示用
  def followers
    member = Member.find(params[:id])
    @members = member.followers.page(params[:page]).per(10)
  end

  private

  def member_params
    params.require(:member).permit(:name, :introduction, :profile_image)
  end
end

app/controllers/member/notifications_controller.rb
class Member::NotificationsController < ApplicationController
  def index
    @notifications = current_member.passive_notifications.order(
      created_at: "DESC"
    ).page(params[:page]).per(10)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/controllers/member/relationships_controller.rb
class Member::RelationshipsController < ApplicationController
  def create
    follow = current_member.active_relationships.new(follower_id: params[:member_id])
    follow.save
    @member = Member.find(params[:member_id])
    @member.create_notification_follow!(current_member)
    redirect_to request.referer
  end

  def destroy
    follow = current_member.active_relationships.find_by(follower_id: params[:member_id])
    follow.destroy
    redirect_to request.referer
  end
end

app/controllers/member/reviews_controller.rb
class Member::ReviewsController < ApplicationController

  def index
    @shop = Shop.find(params[:shop_id])
    @reviews = @shop.reviews.page(params[:page]).per(10).order(created_at: "DESC")
  end

  def new
    @shop = Shop.find(params[:shop_id])
    @review = Review.new
  end

  def create
    @shop = Shop.find(params[:shop_id])
    @review = current_member.reviews.new(review_params)
    @review.shop_id = @shop.id
    review_count = Review.where(shop_id: params[:shop_id]).where(member_id: current_member.id).count
    # バリデーションによるエラーがあるか判定
    if @review.valid?
      # バリデーションエラーが無い、且つレビューを一度もしたことない場合
      if review_count < 1
        @review.save
        redirect_to shop_reviews_path(@shop), notice: "レビューを保存しました"
      else
        redirect_to shop_reviews_path(@shop), notice: "レビューの投稿は一度までです"
      end
    else
      flash.now[:alert] = "レビューの保存に失敗しました"
      render :new
    end
  end

  def edit
    @shop = Shop.find(params[:shop_id])
    @review = Review.find_by(id: params[:id], shop_id: params[:shop_id])
  end

  def update
    @review = Review.find_by(id: params[:id], shop_id: params[:shop_id])
    @review.member_id = current_member.id
    if @review.update(review_params)
      redirect_to shop_reviews_path(shop_id: params[:shop_id]), notice: "レビューを更新しました"
    else
      flash.now[:alert] = "レビューの更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @review = Review.find_by(id: params[:id], shop_id: params[:shop_id])
    @review.destroy
    redirect_to request.referer, notice: "レビューを削除しました"
  end

  private

  def review_params
    params.require(:review).permit(:title, :content, :rate)
  end
end

app/controllers/member/shops_controller.rb
class Member::ShopsController < ApplicationController
  def index
    @shops = Shop.all.page(params[:page]).per(5).order(created_at: "DESC")
  end

  def show
    @shop = Shop.find(params[:id])
    @reviews = @shop.reviews
  end

  def search
    @q = Shop.ransack(params[:q])
    @shops = @q.result(distinct: true).page(params[:page]).per(5)
  end

  def ranking
    # shopのランキング形式用
    @shops = Shop.all
    @shops_rank = @shops.sort_by do |shop|
      shop.reviews.average(:rate).nil? ? 0 : shop.reviews.average(:rate)
    end.reverse
  end

  def map
    @shop = Shop.find(params[:id])
  end

  private

  def shops_params
    params.require(:shop).permit(
      :genre_id,
      :name,
      :phone_number,
      :address,
      :latitude,
      :longitude,
      :nearest_station,
      :business_hours,
      :regular_holiday,
      :main_image_id,
      :caption,
      shop_images_images: []
    )
  end
end

app/controllers/member/tweet_comments_controller.rb
class Member::TweetCommentsController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = TweetComment.new(tweet_comment_paramas)
    comment.member_id = current_member.id
    comment.tweet_id = tweet.id
    comment.save
    redirect_to tweet_path(tweet.id)
  end

  def destroy
    TweetComment.find_by(id: params[:id], tweet_id: params[:tweet_id]).destroy
    redirect_to request.referer
  end

  private

  def tweet_comment_paramas
    params.require(:tweet_comment).permit(:comment)
  end
end

app/controllers/member/tweet_likes_controller.rb
class Member::TweetLikesController < ApplicationController
  def create
    @tweet = Tweet.find(params[:tweet_id])
    tweet_like = current_member.tweet_likes.build(tweet_id: @tweet.id)
    tweet_like.save
    # 通知レコードの作成
    @tweet.create_notification_like!(current_member)
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    tweet_like = current_member.tweet_likes.find_by(tweet_id: @tweet.id)
    tweet_like.destroy
  end
end

app/controllers/member/tweets_controller.rb
class Member::TweetsController < ApplicationController
  def index
    @tweets = Tweet.all.page(params[:page]).per(12).order(created_at: "DESC")
  end

  def show
    @tweet = Tweet.find(params[:id])
    @tweet_comment = TweetComment.new
    @member = @tweet.member
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.member_id = current_member.id
    if @tweet.save
      redirect_to member_path(current_member), notice: "つぶやきを投稿しました"
    else
      flash.now[:alert] = "つぶやき投稿失敗しました"
      render :new
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.member_id = current_member.id
    @tweet.destroy!
    redirect_to member_path(current_member)
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :content, :image)
  end
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_member, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def new_guest
    member = Member.guest
    sign_in member
    redirect_to root_path, notice: "ログインに成功しました"
  end

  protected

  # 会員の論理削除のための記述。退会後は、同じアカウントでは利用できない。
  def reject_member
    @member = Member.find_by(name: params[:memuber][:name])
    if @member
      if @member.deleted_password?(params[:member][:password]) && (@member.is_deleted == false)
        redirect_to new_member_session_path
      end
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  
  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end
  
  def update
    @member = Member.find(params[:id])
    @member.update(member_params)
  end

  def unsubscribe
    @member = Member.find(params[:id])
  end
  
  def withdrawal
    @member = Member.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @member.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
    
  end
  
  private
  
  def member_params
    params.require(:member).permit(:name, :introduction)
  end
  
end

app/views/member/shops/_index.html.erb
<% shops.each do |shop| %>
  <div class="shop-container">
    <div class="shop-top">
      <span id="bookmarks_btn_<%= shop.id %>">
        <%= render partial: 'member/bookmarks/bookmark', locals: {shop: shop} %>
      </span>
      <%= link_to shop.name, shop_path(shop) %>
      <p class="shop-text">/&emsp;<%= shop.genre.name %></p>
    </div>
    <div class="shop-box">
      <div class="shop-image-box">
        <%= attachment_image_tag shop, :main_image, class: "shop-image" %>
      </div>
      <div class="shop-main">
        <div class="shop-caption">
          <p>最寄り駅&emsp;<%= shop.nearest_station %></p>
          <p class="shop-text"><%= simple_format(shop.caption) %></p>
        </div>
        <ul class="review-list">
          <!-- 繰り返し処理を実行してもidを一意に保てるようにreview.idを埋め込む -->
          <li><div id="star-average-<%= shop.id %>"></div></li>
          <li class="review-list-item"><%= shop.reviews.average(:rate).to_f.round(1) %>&emsp;</li>
          <%= render partial: 'member/reviews/star_average', locals: { shop: shop } %>
          <li>
            <%= link_to shop_reviews_path(shop) do %>
            <i class="far fa-comment-dots">&nbsp;<%= shop.reviews.count %>件</i>
          　<% end %>
          </li>
        </ul>
        <!-- レビュー最新の１件のみ表示 -->
        <div class="new-review">
          <% unless shop.reviews.blank? %>
            <% review = Review.where(shop_id: shop.id).order(created_at: :desc).last %>
            <div class="new-review-left">
              <%= attachment_image_tag review.member, :profile_image, fallback: "no_image.jpeg", size: "30x30", class: "profile-image" %><br>
              <% if member_signed_in? %>
            　   <%= link_to review.member.name, member_path(review.member), class: "review-name" %>
            　<% else %>
            　  <span class="review-name"> <%= review.member.name %></span>
            　<% end %>
            </div>
            <div class="new-review-right">
              <span class="review-title"><%= review.title %><br></span>
              <span class="review-content"><%= review.content %><br></span>
            </div>
          <% else %>
            <p class="no-review">まだ口コミ投稿はありません。</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <hr class="border">
<% end %>
<%= paginate shops %>

app/views/member/shops/_link_box.html.erb
<hr class="border">
<div class="link-box">
  <div class="link-item1">
    <%= link_to shop_path(shop), class: "link-item-btn" do %><p>トップ</p><% end %>
  </div>
  <div class="link-item2">
    <%= link_to shop_reviews_path(shop), class: "link-item-btn" do %><p>口コミ</p><% end %>
  </div>
  <div class="link-item3">
    <%= link_to shops_map_path(id: shop.id), class: "link-item-btn" do %><p>地図</p><% end %>
  </div>
</div>
<hr class="border">

app/views/member/shops/_rank_top3.html.erb
<% shops.first(3).each.with_index(1) do |shop, i| %>
  <div class="shop-container">
    <% if i == 1 %>
      <div class="ranking" style="color:#DBB400;">
        <span><i class="fas fa-crown"></i></span>
        <span class="ranking-number">No.<%= i %></span>
      </div>
    <% elsif i == 2 %>
      <div class="ranking" style="color:#AEB3B5;">
        <span><i class="fas fa-crown"></i></span>
        <span class="ranking-number">No.<%= i %></span>
      </div>
    <% elsif i == 3 %>
      <div class="ranking" style="color:#BA6E40;">
        <span><i class="fas fa-crown"></i></span>
        <span class="ranking-number">No.<%= i %></span>
      </div>
    <% end %>
    <div class="shop-top">
      <span id="bookmarks_btn_<%= shop.id %>">
        <%= render partial: 'member/bookmarks/bookmark', locals: {shop: shop} %>
      </span>
      <%= link_to shop.name, shop_path(shop) %>
      <p class="shop-text">/&emsp;<%= shop.genre.name %></p>
    </div>
    <div class="shop-box">
      <div class="shop-image-box">
        <%= attachment_image_tag shop, :main_image, class: "shop-image" %>
      </div>
      <div class="shop-main">
        <div class="shop-caption">
          <p>最寄り駅&emsp;<%= shop.nearest_station %></p>
          <p><%= simple_format(shop.caption) %></p>
        </div>
        <ul class="review-list">
          <!-- 繰り返し処理を実行してもidを一意に保てるようにreview.idを埋め込む -->
          <li><div id="star-average-<%= shop.id %>"></div></li>
          <li class="review-list-item"><%= shop.reviews.average(:rate).to_f.round(1) %>&emsp;</li>
          <%= render partial: 'member/reviews/star_average', locals: { shop: shop } %>
          <li>
            <%= link_to shop_reviews_path(shop) do %>
            <i class="far fa-comment-dots">&nbsp;<%= shop.reviews.count %>件</i>
          　<% end %>
          </li>
        </ul>
        <!-- レビュー最新の１件のみ表示 -->
        <div class="new-review">
          <% unless shop.reviews.blank? %>
            <% review = Review.where(shop_id: shop.id).order(created_at: :desc).last %>
            <div class="new-review-left">
              <%= attachment_image_tag review.member, :profile_image, fallback: "no_image.jpeg", size: "30x30", class: "profile-image" %><br>
              <% if member_signed_in? %>
            　   <%= link_to review.member.name, member_path(review.member), class: "review-name" %>
            　<% else %>
            　  <span class="review-name"> <%= review.member.name %></span>
            　<% end %>
            </div>
            <div class="new-review-right">
              <span class="review-title"><%= review.title %><br></span>
              <span class="review-content"><%= review.content %><br></span>
            </div>
          <% else %>
            <p class="no-review">まだ口コミ投稿はありません。</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<hr class="border">
<% end %>
<p class="next-ranking">
  <%= link_to shops_ranking_path, class: "next-ranking-btn" do %>
    <i class="fas fa-angle-double-right"></i>ランキングの続きを見る
  <% end %>
<p>

app/views/member/shops/index.html.erb
<h3 class="page-heading">Shop</h3>
<%= render  partial: 'member/shops/index', locals: { shops: @shops } %>

app/views/member/shops/map.html.erb
<div class="show-shop-container">
  <div class="show-shop-top">
    <span class="show-shop-name"><%= @shop.name %><p class="shop-text">&emsp;/&emsp;<%= @shop.genre.name %></p></span>
    <ul class="review-list">
      <li><div id="star-average-<%= @shop.id %>"></div></li>
      <li class="review-list-item"><%= @shop.reviews.average(:rate).to_f.round(1) %>&emsp;</li>
      <li>
        <%= link_to shop_reviews_path(@shop) do %>
          <i class="far fa-comment-dots"></i>&nbsp;<%= @shop.reviews.count %>件
      　<% end %>
      </li>
      <%= render partial: 'member/reviews/star_average', locals: { shop: @shop } %>
      <li class="bookmark-size">
        <div id="bookmarks_btn_<%= @shop.id %>">
        <%= render partial: 'member/bookmarks/bookmark', locals: {shop: @shop} %>
      </li>
    </ul>
  </div>
  <%= render partial: 'member/shops/link_box', locals: { shop: @shop } %>
  <div class="map-area">
    <h5>アクセス</h5>
    <p class="shop-caption">最寄り駅&emsp;<%= @shop.nearest_station %></p>
    <%= render 'layouts/map' %>
    <!--mapの表示-->
    <div id="map"></div>
  </div>
</div>

app/views/member/shops/ranking.html.erb
<h3 class="page-heading">Ranking</h3>
<%= render partial: 'member/shops/rank_top10', locals: { shops: @shops_rank } %>

app/views/member/shops/search.html.erb
<h3 class="page-heading">Search Shop</h3>
<% @shops.each do |shop| %>
<div class="shop-container">
  <div class="shop-top">
    <span id="bookmarks_btn_<%= shop.id %>">
      <%= render partial: 'member/bookmarks/bookmark', locals: {shop: shop} %>
    </span>
    <%= link_to shop.name, shop_path(shop) %>
    <p class="shop-text">/&emsp;<%= shop.genre.name %></p>
  </div>
  <div class="shop-box">
    <div class="shop-image-box">
      <%= attachment_image_tag shop, :main_image, size: '240x180', class: "shop-image" %>
    </div>
    <div class="shop-main">
      <p>最寄り駅&emsp;<%= shop.nearest_station %></p>
      <p><%= shop.caption %></p>
      <ul class="review-list">
        <!-- 繰り返し処理を実行してもidを一意に保てるようにreview.idを埋め込む -->
        <li><div id="star-average-<%= shop.id %>"></div></li>
        <li><%= shop.reviews.average(:rate).to_i.round(1) %>&emsp;</li>
        <li>
          <%= link_to shop_reviews_path(shop) do %>
            <i class="far fa-comment-dots">&nbsp;<%= shop.reviews.count %>件</i>
          <% end %>
        </li>
        <%= render partial: 'member/reviews/star_average', locals: { shop: shop } %>
      </ul>
      <!-- レビュー最新の１件のみ表示 -->
      <div class="new-review">
        <% unless shop.reviews.blank? %>
          <% last_reviews = Review.where(shop_id: shop.id).order(created_at: :desc).limit(1) %>
          <% last_reviews.each do |review| %>
            <div class="new-review-left">
              <%= attachment_image_tag review.member, :profile_image, fallback: "no_image.jpeg", size: "30x30", class: "profile-image" %><br>
            　<%= link_to review.member.name, member_path(review.member), class: "review-name" %>
            </div>
            <div class="new-review-right">
              <span class="review-title"><%= review.title %><br></span>
              <span class="review-content"><%= review.content %><br></span>
            </div>
          <% end %>
        <% else %>
          <p class="no-review">まだ口コミ投稿はありません。</p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<hr class="border">
<% end %>